const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function n(v){const x=parseFloat(v);return Number.isFinite(x)?x:0}function fmt(v,d=1){if(!Number.isFinite(v))return"—";const r=Math.round(v*(10**d))/(10**d);return r.toLocaleString("ja-JP",{maximumFractionDigits:d})}function gcdInt(a,b){a=Math.abs(a);b=Math.abs(b);while(b){[a,b]=[b,a%b]}return a||1}function ratioFromValues(values){const p=values.filter(v=>v>0);if(p.length<2)return p.length===1?"1":"—";const s=p.map(v=>Math.round(v*10));let g=s[0];for(const v of s.slice(1))g=gcdInt(g,v);let q=s.map(v=>v/g);if(Math.max(...q)>50){const m=Math.min(...p);q=p.map(v=>Math.round(v/m*10)/10)}return q.map(v=>fmt(v,1)).join(" : ")}
const rows=$("#mixRows"),tpl=$("#rowTemplate");
function addRow(name="",abv="",amount="",dilution=1){const node=tpl.content.firstElementChild.cloneNode(true);$(".name",node).value=name;$(".abv",node).value=abv;$(".amount",node).value=amount;$(".dilution",node).value=dilution||1;$$('input',node).forEach(el=>el.addEventListener('input',calcMix));$(".delete",node).addEventListener('click',()=>{node.remove();if(!rows.children.length)addRow();calcMix()});rows.appendChild(node);calcMix();return node}
function getMixData(){return $$(".mix-row",rows).map(r=>({row:r,name:$(".name",r).value.trim()||"材料",amount:n($(".amount",r).value),abv:n($(".abv",r).value),dilution:Math.max(1,n($(".dilution",r).value)||1)}))}
function calcMix(){const data=getMixData(),total=data.reduce((s,x)=>s+x.amount,0),alcohol=data.reduce((s,x)=>s+x.amount*x.abv/100,0),abv=total>0?alcohol/total*100:0;$("#mixTotal").textContent=`${fmt(total,1)} ml`;$("#mixAbv").textContent=`${fmt(abv,2)} %`;const active=data.filter(x=>x.amount>0);$("#mixRatio").textContent=ratioFromValues(active.map(x=>x.amount));$("#mixBreakdown").textContent=active.length?active.map(x=>`${x.name} ${fmt(x.amount,1)}ml${x.dilution>1?`（${fmt(x.dilution,1)}倍）`:''}`).join(' / '):'材料を入力すると表示されます';const guide=$("#dilutionGuide"),diluted=active.filter(x=>x.dilution>1);if(!diluted.length){guide.classList.add('hidden');guide.innerHTML=''}else{guide.innerHTML=diluted.map(x=>{const rt=x.amount*x.dilution,rd=x.amount*(x.dilution-1),oa=Math.max(0,total-x.amount),diff=oa-rd;let status=Math.abs(diff)<.05?'✓ ちょうど':diff>0?`割り材が ${fmt(diff,1)}ml 多め`:`割り材が ${fmt(-diff,1)}ml 不足`;return `<div><strong>${x.name} ${fmt(x.dilution,1)}倍</strong><br>原液 ${fmt(x.amount,1)}ml → 完成時に必要な全体量 ${fmt(rt,1)}ml（原液以外 ${fmt(rd,1)}ml）<br><b>${status}</b></div>`}).join('');guide.classList.remove('hidden')}}
function scaleMixToTarget(){const w=$("#scaleWarning");w.classList.add('hidden');w.textContent='';const target=n($("#mixTargetTotal").value),data=getMixData(),current=data.reduce((s,x)=>s+x.amount,0);if(target<=0){w.textContent='完成量を0より大きい値で入力してください。';w.classList.remove('hidden');return}if(current<=0){w.textContent='先に材料の量を入力して割合を決めてください。';w.classList.remove('hidden');return}const f=target/current,active=data.filter(x=>x.amount>0),targetTenths=Math.round(target*10),exact=active.map(x=>x.amount*f*10),tenths=exact.map(v=>Math.max(1,Math.floor(v)));let rem=targetTenths-tenths.reduce((s,v)=>s+v,0);const order=exact.map((v,i)=>[i,v-Math.floor(v)]).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);for(let k=0;rem>0&&k<order.length*2;k++){tenths[order[k%order.length]]++;rem--}while(rem<0){const c=tenths.map((v,i)=>[i,v]).filter(x=>x[1]>1).sort((a,b)=>b[1]-a[1]);if(!c.length)break;tenths[c[0][0]]--;rem++}active.forEach((x,i)=>{$(".amount",x.row).value=(tenths[i]/10).toString()});calcMix()}
$("#scaleMixBtn").addEventListener('click',scaleMixToTarget);$("#mixTargetTotal").addEventListener('keydown',e=>{if(e.key==='Enter')scaleMixToTarget()});$("#addRowBtn").addEventListener('click',()=>addRow());

const FAVORITE_KEY='warimono-favorites-v1';const defaults=[{name:'ウイスキー',abv:40,dilution:1},{name:'焼酎',abv:25,dilution:1},{name:'炭酸水',abv:0,dilution:1},{name:'水',abv:0,dilution:1},{name:'カルピス原液',abv:0,dilution:5}];
function loadFavorites(){try{const x=JSON.parse(localStorage.getItem(FAVORITE_KEY));return Array.isArray(x)&&x.length?x:defaults}catch{return defaults}}function saveFavorites(items){localStorage.setItem(FAVORITE_KEY,JSON.stringify(items))}let favorites=loadFavorites();
function labelFavorite(x){return `${x.name}${x.abv>0?` ${fmt(x.abv,1)}%`:''}${x.dilution>1?` ${fmt(x.dilution,1)}倍`:''}`}
function useFavorite(x){const empty=$$(".mix-row",rows).find(r=>!$(".name",r).value&&!$(".amount",r).value),row=empty||addRow();$(".name",row).value=x.name;$(".abv",row).value=x.abv;$(".dilution",row).value=x.dilution||1;$(".amount",row).focus();calcMix()}
function renderFavorites(){const box=$("#favoriteChips");box.innerHTML='';favorites.forEach(x=>{const b=document.createElement('button');b.type='button';b.textContent=labelFavorite(x);b.addEventListener('click',()=>useFavorite(x));box.appendChild(b)})}
function openFavoriteModal(index=''){const edit=index!==''?favorites[index]:null;$("#favoriteModalTitle").textContent=edit?'よく使う材料を編集':'よく使う材料を登録';$("#favoriteName").value=edit?.name||'';$("#favoriteAbv").value=edit?.abv??0;$("#favoriteDilution").value=edit?.dilution??1;$("#favoriteEditIndex").value=index;$("#favoriteFormWarning").classList.add('hidden');$("#favoriteModal").classList.remove('hidden');$("#favoriteModal").setAttribute('aria-hidden','false');setTimeout(()=>$("#favoriteName").focus(),50)}function closeFavoriteModal(){$("#favoriteModal").classList.add('hidden');$("#favoriteModal").setAttribute('aria-hidden','true')}
function renderManager(){const box=$("#favoriteManagerList");box.innerHTML='';favorites.forEach((x,i)=>{const row=document.createElement('div');row.className='favorite-manager-row';row.innerHTML=`<div><strong>${x.name}</strong><small>${x.abv}% / ${x.dilution>1?`${x.dilution}倍`:'希釈なし'}</small></div><div class="manager-actions"><button class="edit-fav">編集</button><button class="delete-fav">削除</button></div>`;$('.edit-fav',row).addEventListener('click',()=>{closeManager();openFavoriteModal(i)});$('.delete-fav',row).addEventListener('click',()=>{favorites.splice(i,1);if(!favorites.length)favorites=[...defaults];saveFavorites(favorites);renderFavorites();renderManager()});box.appendChild(row)})}
function openManager(){renderManager();$("#favoriteManager").classList.remove('hidden');$("#favoriteManager").setAttribute('aria-hidden','false')}function closeManager(){$("#favoriteManager").classList.add('hidden');$("#favoriteManager").setAttribute('aria-hidden','true')}
$("#addFavoriteBtn").addEventListener('click',()=>openFavoriteModal());$("#manageFavoritesBtn").addEventListener('click',openManager);$("#closeFavoriteModal").addEventListener('click',closeFavoriteModal);$("#closeFavoriteManager").addEventListener('click',closeManager);$("#managerAddBtn").addEventListener('click',()=>{closeManager();openFavoriteModal()});
$("#saveFavoriteBtn").addEventListener('click',()=>{const name=$("#favoriteName").value.trim(),abv=n($("#favoriteAbv").value),dilution=Math.max(1,n($("#favoriteDilution").value)||1),w=$("#favoriteFormWarning");if(!name){w.textContent='材料名を入力してください。';w.classList.remove('hidden');return}if(abv<0||abv>100){w.textContent='アルコール度数は0〜100%で入力してください。';w.classList.remove('hidden');return}const item={name,abv,dilution},idx=$("#favoriteEditIndex").value;if(idx==='')favorites.push(item);else favorites[Number(idx)]=item;saveFavorites(favorites);renderFavorites();closeFavoriteModal()});
[$("#favoriteModal"),$("#favoriteManager")].forEach(m=>m.addEventListener('click',e=>{if(e.target===m){m=== $("#favoriteModal")?closeFavoriteModal():closeManager()}}));

function calcDilute(){const total=n($("#diluteTotal").value),factor=n($("#diluteFactor").value),warn=$("#diluteWarning");warn.classList.add('hidden');warn.textContent='';let base=0,mixer=0,valid=false;if(total<=0){warn.textContent='完成量を0より大きい値で入力してください。';warn.classList.remove('hidden')}else if(factor<1){warn.textContent='希釈倍率は1倍以上で入力してください。（1倍＝希釈なし）';warn.classList.remove('hidden')}else{valid=true;base=total/factor;mixer=Math.max(0,total-base)}$("#diluteBase").textContent=`${fmt(base,1)} ml`;$("#diluteMixer").textContent=`${fmt(mixer,1)} ml`;$("#diluteRatio").textContent=valid?`1 : ${fmt(factor-1,1)}`:'—'}['#diluteTotal','#diluteFactor'].forEach(s=>$(s).addEventListener('input',calcDilute));
function calcReverse(){const source=n($("#reverseSourceAbv").value),target=n($("#reverseTargetAbv").value),total=n($("#reverseTotal").value),warn=$("#reverseWarning");warn.classList.add('hidden');warn.textContent='';let spirit=0,mixer=0;if(total<=0){warn.textContent='完成量を0より大きい値で入力してください。';warn.classList.remove('hidden')}else if(source<=0){warn.textContent='元のお酒の度数は0%より大きい値を入力してください。';warn.classList.remove('hidden')}else if(target>source){warn.textContent='目標度数は元のお酒の度数以下にしてください。';warn.classList.remove('hidden')}else{spirit=total*(target/source);mixer=Math.max(0,total-spirit)}$("#reverseSpirit").textContent=`${fmt(spirit,1)} ml`;$("#reverseMixer").textContent=`${fmt(mixer,1)} ml`;$("#reverseRatio").textContent=spirit>0?ratioFromValues([spirit,mixer]):'—'}['#reverseSourceAbv','#reverseTargetAbv','#reverseTotal'].forEach(s=>$(s).addEventListener('input',calcReverse));
$$('.tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===tab));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===tab.dataset.tab))}));
$("#resetBtn").addEventListener('click',()=>{rows.innerHTML='';addRow('カルピス原液',0,50,5);addRow('焼酎',25,60,1);addRow('炭酸水',0,140,1);$("#mixTargetTotal").value='';$("#diluteTotal").value=500;$("#diluteFactor").value=5;$("#reverseSourceAbv").value=40;$("#reverseTargetAbv").value=5;$("#reverseTotal").value=500;calcDilute();calcReverse()});
renderFavorites();addRow('カルピス原液',0,50,5);addRow('焼酎',25,60,1);addRow('炭酸水',0,140,1);calcDilute();calcReverse();
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
